<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Young Eun Jeon, Jeong-Wook Lee, and Jung-In Seo">

<title>7&nbsp; LASSO Regression – Machine Learning with Hyperparameter Tuning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ridge.html" rel="next">
<link href="./SVM_rd.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-1092c56c6cadf2eb47b1bc8063ab382a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ef31e3f4d9d6eef55c54bdf6b9cd68ca.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./index.html">Welcome</a></li><li class="breadcrumb-item"><a href="./LASSO.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">LASSO Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Machine Learning with Hyperparameter Tuning</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/JJJJYE/ML_book2" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./KNN.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Nearest Neighborhood Algorithm</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Cluster Analysis based on k-means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Decision_tree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Decision Tree</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SVM_li.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Support Vector Machine with Linear Kernel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SVM_po.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Support Vector Machine with Polynomial Kernel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SVM_rd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Support Vector Machine with Radial Basis Kernel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./LASSO.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">LASSO Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ridge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Ridge Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Elasticnet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Elastic Net Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RF.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Random Forest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./AdaBoost.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">AdaBoost</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./GBM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Gradient Boosting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./XGBoost.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">XGBoost</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#데이터-불러오기" id="toc-데이터-불러오기" class="nav-link active" data-scroll-target="#데이터-불러오기"><span class="header-section-number">7.1</span> 데이터 불러오기</a></li>
  <li><a href="#데이터-전처리-i" id="toc-데이터-전처리-i" class="nav-link" data-scroll-target="#데이터-전처리-i"><span class="header-section-number">7.2</span> 데이터 전처리 I</a></li>
  <li><a href="#데이터-탐색" id="toc-데이터-탐색" class="nav-link" data-scroll-target="#데이터-탐색"><span class="header-section-number">7.3</span> 데이터 탐색</a></li>
  <li><a href="#데이터-분할" id="toc-데이터-분할" class="nav-link" data-scroll-target="#데이터-분할"><span class="header-section-number">7.4</span> 데이터 분할</a></li>
  <li><a href="#데이터-전처리-ii" id="toc-데이터-전처리-ii" class="nav-link" data-scroll-target="#데이터-전처리-ii"><span class="header-section-number">7.5</span> 데이터 전처리 II</a></li>
  <li><a href="#모형-훈련" id="toc-모형-훈련" class="nav-link" data-scroll-target="#모형-훈련"><span class="header-section-number">7.6</span> 모형 훈련</a></li>
  <li><a href="#모형-평가" id="toc-모형-평가" class="nav-link" data-scroll-target="#모형-평가"><span class="header-section-number">7.7</span> 모형 평가</a>
  <ul class="collapse">
  <li><a href="#confusionmatrix" id="toc-confusionmatrix" class="nav-link" data-scroll-target="#confusionmatrix"><span class="header-section-number">7.7.1</span> ConfusionMatrix</a></li>
  <li><a href="#roc-곡선" id="toc-roc-곡선" class="nav-link" data-scroll-target="#roc-곡선"><span class="header-section-number">7.7.2</span> ROC 곡선</a></li>
  <li><a href="#향상-차트" id="toc-향상-차트" class="nav-link" data-scroll-target="#향상-차트"><span class="header-section-number">7.7.3</span> 향상 차트</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/JJJJYE/ML_book2/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./index.html">Welcome</a></li><li class="breadcrumb-item"><a href="./LASSO.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">LASSO Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">LASSO Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>LASSO Regression의 장점</p>
</blockquote>
<ul>
<li>규제항을 통해 회귀계수를 “0”으로 추정하기 때문에 변수 선택이 가능하다.</li>
</ul>
<p><br></p>
<blockquote class="blockquote">
<p>LASSO Regression의 단점</p>
</blockquote>
<ul>
<li>예측 변수의 개수가 표본의 크기보다 큰 경우, 볼록 최적화 문제의 특성 때문에 표본의 크기보다 많은 예측 변수를 선택할 수 없다.</li>
<li>예측 변수 사이에 어떤 그룹 구조(쌍별 상관 관계가 매우 높은)가 있을 때, 그룹에서 하나의 예측 변수만 선택한다.</li>
<li>예측 변수의 개수가 표본의 크기보다 큰 상황에서 예측 변수들이 높은 상관관계를 가지고 있을 때, <code>Ridge Regression</code>보다 예측 성능이 낮다.</li>
</ul>
<p><br></p>
<blockquote class="blockquote">
<p>실습 자료 : 1912년 4월 15일 타이타닉호 침몰 당시 탑승객들의 정보를 기록한 데이터셋이며, 총 11개의 변수를 포함하고 있다. 이 자료에서 <strong>Target</strong>은 <code>Survived</code>이다.</p>
</blockquote>
<center>
<img src="./image/그림_titanic.png" class="img-fluid">
</center>
<p><br></p>
<center>
<img src="./image/Titanic_표.png" width="400" height="400">
</center>
<p><br></p>
<section id="데이터-불러오기" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="데이터-불러오기"><span class="header-section-number">7.1</span> 데이터 불러오기</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(<span class="st">"data.table"</span>, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"tidyverse"</span>, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"dplyr"</span>, <span class="st">"tidyr"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"ggplot2"</span>, <span class="st">"GGally"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"caret"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>               <span class="st">"doParallel"</span>, <span class="st">"parallel"</span>)                                <span class="co"># For 병렬 처리</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoParallel</span>(<span class="at">cores=</span><span class="fu">detectCores</span>())                                 <span class="co"># 사용할 Core 개수 지정     </span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>titanic <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"../Titanic.csv"</span>)                                      <span class="co"># 데이터 불러오기</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>titanic <span class="sc">%&gt;%</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  as_tibble</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 891 × 11
   Survived Pclass Name                                                Sex      Age SibSp Parch Ticket            Fare Cabin  Embarked
      &lt;int&gt;  &lt;int&gt; &lt;chr&gt;                                               &lt;chr&gt;  &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;   
 1        0      3 Braund, Mr. Owen Harris                             male      22     1     0 A/5 21171         7.25 ""     S       
 2        1      1 Cumings, Mrs. John Bradley (Florence Briggs Thayer) female    38     1     0 PC 17599         71.3  "C85"  C       
 3        1      3 Heikkinen, Miss. Laina                              female    26     0     0 STON/O2. 3101282  7.92 ""     S       
 4        1      1 Futrelle, Mrs. Jacques Heath (Lily May Peel)        female    35     1     0 113803           53.1  "C123" S       
 5        0      3 Allen, Mr. William Henry                            male      35     0     0 373450            8.05 ""     S       
 6        0      3 Moran, Mr. James                                    male      NA     0     0 330877            8.46 ""     Q       
 7        0      1 McCarthy, Mr. Timothy J                             male      54     0     0 17463            51.9  "E46"  S       
 8        0      3 Palsson, Master. Gosta Leonard                      male       2     3     1 349909           21.1  ""     S       
 9        1      3 Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   female    27     0     2 347742           11.1  ""     S       
10        1      2 Nasser, Mrs. Nicholas (Adele Achem)                 female    14     1     0 237736           30.1  ""     C       
# ℹ 881 more rows</code></pre>
</div>
</div>
</section>
<section id="데이터-전처리-i" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="데이터-전처리-i"><span class="header-section-number">7.2</span> 데이터 전처리 I</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>titanic <span class="sc">%&lt;&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>() <span class="sc">%&gt;%</span>                                                      <span class="co"># Data Frame 형태로 변환 </span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Survived =</span> <span class="fu">ifelse</span>(Survived <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"yes"</span>, <span class="st">"no"</span>))                 <span class="co"># Target을 문자형 변수로 변환</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Convert to Factor</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>fac.col <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Pclass"</span>, <span class="st">"Sex"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>             <span class="co"># Target</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Survived"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>titanic <span class="ot">&lt;-</span> titanic <span class="sc">%&gt;%</span> </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(fac.col, as.factor)                                         <span class="co"># 범주형으로 변환</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(titanic)                                                        <span class="co"># 데이터 구조 확인</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 891
Columns: 11
$ Survived &lt;fct&gt; no, yes, yes, yes, no, no, no, no, yes, yes, yes, yes, no, no, no, yes, no, yes, no, yes, no, yes, yes, yes, no, yes, no, no, yes, no, no, yes, yes, no, no, no, yes, no, no, yes, no…
$ Pclass   &lt;fct&gt; 3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 1, 3, 3, 3, 1, 3, 3, 1, 1, 3, 2, 1, 1, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 1, 1, 2, 3, 2, 3, 3…
$ Name     &lt;chr&gt; "Braund, Mr. Owen Harris", "Cumings, Mrs. John Bradley (Florence Briggs Thayer)", "Heikkinen, Miss. Laina", "Futrelle, Mrs. Jacques Heath (Lily May Peel)", "Allen, Mr. William Henry…
$ Sex      &lt;fct&gt; male, female, female, female, male, male, male, male, female, female, female, female, male, male, female, female, male, male, female, female, male, male, female, male, female, femal…
$ Age      &lt;dbl&gt; 22.0, 38.0, 26.0, 35.0, 35.0, NA, 54.0, 2.0, 27.0, 14.0, 4.0, 58.0, 20.0, 39.0, 14.0, 55.0, 2.0, NA, 31.0, NA, 35.0, 34.0, 15.0, 28.0, 8.0, 38.0, NA, 19.0, NA, NA, 40.0, NA, NA, 66.…
$ SibSp    &lt;int&gt; 1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 1, 0, 0, 1, 0, 0, 4, 0, 1, 0, 0, 0, 0, 0, 3, 1, 0, 3, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 2, 1, 4, 0, 1, 1, 0, 0, 0, 0, 1, 5, 0…
$ Parch    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 5, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 2, 0…
$ Ticket   &lt;chr&gt; "A/5 21171", "PC 17599", "STON/O2. 3101282", "113803", "373450", "330877", "17463", "349909", "347742", "237736", "PP 9549", "113783", "A/5. 2151", "347082", "350406", "248706", "38…
$ Fare     &lt;dbl&gt; 7.2500, 71.2833, 7.9250, 53.1000, 8.0500, 8.4583, 51.8625, 21.0750, 11.1333, 30.0708, 16.7000, 26.5500, 8.0500, 31.2750, 7.8542, 16.0000, 29.1250, 13.0000, 18.0000, 7.2250, 26.0000,…
$ Cabin    &lt;chr&gt; "", "C85", "", "C123", "", "", "E46", "", "", "", "G6", "C103", "", "", "", "", "", "", "", "", "", "D56", "", "A6", "", "", "", "C23 C25 C27", "", "", "", "B78", "", "", "", "", ""…
$ Embarked &lt;chr&gt; "S", "C", "S", "S", "S", "Q", "S", "S", "S", "C", "S", "S", "S", "S", "S", "S", "Q", "S", "S", "C", "S", "S", "Q", "S", "S", "S", "C", "S", "Q", "S", "C", "C", "Q", "S", "C", "S", "…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Generate New Variable</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>titanic <span class="ot">&lt;-</span> titanic <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">FamSize =</span> SibSp <span class="sc">+</span> Parch)                                       <span class="co"># "FamSize = 형제 및 배우자 수 + 부모님 및 자녀 수"로 가족 수를 의미하는 새로운 변수</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(titanic)                                                        <span class="co"># 데이터 구조 확인</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 891
Columns: 12
$ Survived &lt;fct&gt; no, yes, yes, yes, no, no, no, no, yes, yes, yes, yes, no, no, no, yes, no, yes, no, yes, no, yes, yes, yes, no, yes, no, no, yes, no, no, yes, yes, no, no, no, yes, no, no, yes, no…
$ Pclass   &lt;fct&gt; 3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 1, 3, 3, 3, 1, 3, 3, 1, 1, 3, 2, 1, 1, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 1, 1, 2, 3, 2, 3, 3…
$ Name     &lt;chr&gt; "Braund, Mr. Owen Harris", "Cumings, Mrs. John Bradley (Florence Briggs Thayer)", "Heikkinen, Miss. Laina", "Futrelle, Mrs. Jacques Heath (Lily May Peel)", "Allen, Mr. William Henry…
$ Sex      &lt;fct&gt; male, female, female, female, male, male, male, male, female, female, female, female, male, male, female, female, male, male, female, female, male, male, female, male, female, femal…
$ Age      &lt;dbl&gt; 22.0, 38.0, 26.0, 35.0, 35.0, NA, 54.0, 2.0, 27.0, 14.0, 4.0, 58.0, 20.0, 39.0, 14.0, 55.0, 2.0, NA, 31.0, NA, 35.0, 34.0, 15.0, 28.0, 8.0, 38.0, NA, 19.0, NA, NA, 40.0, NA, NA, 66.…
$ SibSp    &lt;int&gt; 1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 1, 0, 0, 1, 0, 0, 4, 0, 1, 0, 0, 0, 0, 0, 3, 1, 0, 3, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 2, 1, 4, 0, 1, 1, 0, 0, 0, 0, 1, 5, 0…
$ Parch    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 5, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 2, 0…
$ Ticket   &lt;chr&gt; "A/5 21171", "PC 17599", "STON/O2. 3101282", "113803", "373450", "330877", "17463", "349909", "347742", "237736", "PP 9549", "113783", "A/5. 2151", "347082", "350406", "248706", "38…
$ Fare     &lt;dbl&gt; 7.2500, 71.2833, 7.9250, 53.1000, 8.0500, 8.4583, 51.8625, 21.0750, 11.1333, 30.0708, 16.7000, 26.5500, 8.0500, 31.2750, 7.8542, 16.0000, 29.1250, 13.0000, 18.0000, 7.2250, 26.0000,…
$ Cabin    &lt;chr&gt; "", "C85", "", "C123", "", "", "E46", "", "", "", "G6", "C103", "", "", "", "", "", "", "", "", "", "D56", "", "A6", "", "", "", "C23 C25 C27", "", "", "", "B78", "", "", "", "", ""…
$ Embarked &lt;chr&gt; "S", "C", "S", "S", "S", "Q", "S", "S", "S", "C", "S", "S", "S", "S", "S", "S", "Q", "S", "S", "C", "S", "S", "Q", "S", "S", "S", "C", "S", "Q", "S", "C", "C", "Q", "S", "C", "S", "…
$ FamSize  &lt;int&gt; 1, 1, 0, 1, 0, 0, 0, 4, 2, 1, 2, 0, 0, 6, 0, 0, 5, 0, 1, 0, 0, 0, 0, 0, 4, 6, 0, 5, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 3, 0, 0, 1, 0, 2, 1, 5, 0, 1, 1, 1, 0, 0, 0, 3, 7, 0…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Select Variables used for Analysis</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>titanic1 <span class="ot">&lt;-</span> titanic <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Survived, Pclass, Sex, Age, Fare, FamSize)                     <span class="co"># 분석에 사용할 변수 선택</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>titanic1 <span class="sc">%&gt;%</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  as_tibble</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 891 × 6
   Survived Pclass Sex      Age  Fare FamSize
   &lt;fct&gt;    &lt;fct&gt;  &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt;
 1 no       3      male      22  7.25       1
 2 yes      1      female    38 71.3        1
 3 yes      3      female    26  7.92       0
 4 yes      1      female    35 53.1        1
 5 no       3      male      35  8.05       0
 6 no       3      male      NA  8.46       0
 7 no       1      male      54 51.9        0
 8 no       3      male       2 21.1        4
 9 yes      3      female    27 11.1        2
10 yes      2      female    14 30.1        1
# ℹ 881 more rows</code></pre>
</div>
</div>
</section>
<section id="데이터-탐색" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="데이터-탐색"><span class="header-section-number">7.3</span> 데이터 탐색</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(titanic1,                                        </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(<span class="at">colour =</span> Survived)) <span class="sc">+</span>                         <span class="co"># Target의 범주에 따라 색깔을 다르게 표현</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LASSO_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(titanic1,                                     </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(<span class="at">colour =</span> Survived, <span class="at">alpha =</span> <span class="fl">0.8</span>)) <span class="sc">+</span>            <span class="co"># Target의 범주에 따라 색깔을 다르게 표현</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#00798c"</span>, <span class="st">"#d1495b"</span>)) <span class="sc">+</span> <span class="co"># 특정 색깔 지정</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#00798c"</span>, <span class="st">"#d1495b"</span>)) <span class="sc">+</span>   <span class="co"># 특정 색깔 지정</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LASSO_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="데이터-분할" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="데이터-분할"><span class="header-section-number">7.4</span> 데이터 분할</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Partition (Training Dataset : Test Dataset = 7:3)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>y      <span class="ot">&lt;-</span> titanic1<span class="sc">$</span>Survived                             <span class="co"># Target</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>ind    <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(y, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list  =</span>T)     <span class="co"># Index를 이용하여 7:3으로 분할</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>titanic.trd <span class="ot">&lt;-</span> titanic1[ind<span class="sc">$</span>Resample1,]                 <span class="co"># Training Dataset</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>titanic.ted <span class="ot">&lt;-</span> titanic1[<span class="sc">-</span>ind<span class="sc">$</span>Resample1,]                <span class="co"># Test Dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="데이터-전처리-ii" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="데이터-전처리-ii"><span class="header-section-number">7.5</span> 데이터 전처리 II</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Imputation</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>titanic.trd.Imp <span class="ot">&lt;-</span> titanic.trd <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Age =</span> <span class="fu">replace_na</span>(Age, <span class="fu">mean</span>(Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))                 <span class="co"># 평균으로 결측값 대체</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>titanic.ted.Imp <span class="ot">&lt;-</span> titanic.ted <span class="sc">%&gt;%</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Age =</span> <span class="fu">replace_na</span>(Age, <span class="fu">mean</span>(titanic.trd<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))     <span class="co"># Training Dataset을 이용하여 결측값 대체</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(titanic.trd.Imp)                                                 <span class="co"># 데이터 구조 확인</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 625
Columns: 6
$ Survived &lt;fct&gt; no, yes, yes, no, no, no, yes, yes, yes, yes, no, no, yes, no, yes, no, yes, no, no, no, yes, no, no, yes, yes, no, no, no, no, no, yes, no, no, no, yes, no, yes, no, no, no, yes, n…
$ Pclass   &lt;fct&gt; 3, 3, 1, 3, 3, 3, 3, 2, 3, 1, 3, 3, 2, 3, 3, 2, 1, 3, 3, 1, 3, 3, 1, 1, 3, 2, 1, 1, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 1, 2, 3…
$ Sex      &lt;fct&gt; male, female, female, male, male, male, female, female, female, female, male, female, male, female, female, male, male, female, male, male, female, male, male, female, female, male,…
$ Age      &lt;dbl&gt; 22.00000, 26.00000, 35.00000, 35.00000, 29.93737, 2.00000, 27.00000, 14.00000, 4.00000, 58.00000, 39.00000, 14.00000, 29.93737, 31.00000, 29.93737, 35.00000, 28.00000, 8.00000, 29.9…
$ Fare     &lt;dbl&gt; 7.2500, 7.9250, 53.1000, 8.0500, 8.4583, 21.0750, 11.1333, 30.0708, 16.7000, 26.5500, 31.2750, 7.8542, 13.0000, 18.0000, 7.2250, 26.0000, 35.5000, 21.0750, 7.2250, 263.0000, 7.8792,…
$ FamSize  &lt;int&gt; 1, 0, 1, 0, 0, 4, 2, 1, 2, 0, 6, 0, 0, 1, 0, 0, 0, 4, 0, 5, 0, 0, 0, 1, 0, 0, 1, 1, 0, 2, 1, 1, 1, 0, 0, 1, 0, 2, 1, 5, 1, 1, 0, 7, 0, 0, 5, 0, 2, 7, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(titanic.ted.Imp)                                                 <span class="co"># 데이터 구조 확인</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 266
Columns: 6
$ Survived &lt;fct&gt; yes, no, no, yes, no, yes, yes, yes, yes, yes, no, no, yes, yes, no, yes, no, yes, yes, no, yes, no, no, no, no, no, no, yes, yes, no, no, no, no, no, no, no, no, no, no, yes, no, n…
$ Pclass   &lt;fct&gt; 1, 1, 3, 2, 3, 2, 3, 3, 3, 2, 3, 3, 2, 2, 3, 2, 1, 3, 2, 3, 3, 2, 2, 3, 3, 3, 3, 1, 2, 2, 3, 3, 3, 3, 3, 2, 3, 2, 2, 2, 3, 3, 2, 1, 3, 1, 3, 2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3…
$ Sex      &lt;fct&gt; female, male, male, female, male, male, female, female, male, female, male, male, female, female, male, female, male, male, female, male, female, male, male, male, male, male, male,…
$ Age      &lt;dbl&gt; 38.00000, 54.00000, 20.00000, 55.00000, 2.00000, 34.00000, 15.00000, 38.00000, 29.93737, 3.00000, 29.93737, 21.00000, 29.00000, 21.00000, 28.50000, 5.00000, 45.00000, 29.93737, 29.0…
$ Fare     &lt;dbl&gt; 71.2833, 51.8625, 8.0500, 16.0000, 29.1250, 13.0000, 8.0292, 31.3875, 7.2292, 41.5792, 8.0500, 7.8000, 26.0000, 10.5000, 7.2292, 27.7500, 83.4750, 15.2458, 10.5000, 8.1583, 7.9250, …
$ FamSize  &lt;int&gt; 1, 0, 0, 0, 5, 0, 0, 6, 0, 3, 0, 0, 1, 0, 0, 3, 1, 2, 0, 0, 6, 0, 0, 0, 0, 4, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 6, 2, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 1, 5, 2, 5, 0, 5, 0, 4, 0, 6…</code></pre>
</div>
</div>
</section>
<section id="모형-훈련" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="모형-훈련"><span class="header-section-number">7.6</span> 모형 훈련</h2>
<p>Package <code>"caret"</code>은 통합 API를 통해 R로 기계 학습을 실행할 수 있는 매우 실용적인 방법을 제공한다. Package <code>"caret"</code>를 통해 <code>LASSO Regression</code>을 수행하기 위해 옵션 <code>method</code>에 다양한 방법(Ex: <code>"lasso"</code>, <code>"blasso"</code> 등)을 입력할 수 있지만, 대부분 회귀 문제에 대해서만 분석이 가능하다. 분류와 회귀 문제 모두 가능한 <code>"glmnet"</code>을 이용하려면 옵션 <code>tuneGrid = expand.grid()</code>을 통해 탐색하고자 하는 초모수 <code>lambda</code>의 범위를 직접 지정해줘야 한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fitControl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">5</span>,                 <span class="co"># 5-Fold Cross Validation (5-Fold CV)</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">allowParallel =</span> <span class="cn">TRUE</span>)                      <span class="co"># 병렬 처리</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)                                                         <span class="co"># For CV</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>lasso.fit <span class="ot">&lt;-</span> <span class="fu">train</span>(Survived <span class="sc">~</span> ., <span class="at">data =</span> titanic.trd.Imp, </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">trControl =</span> fitControl ,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">"glmnet"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">alpha =</span> <span class="dv">1</span>,                  <span class="co"># For LASSO Regression</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">lambda =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.001</span>)), <span class="co"># lambda의 탐색 범위</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">preProc =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>))                    <span class="co"># Standardization for 예측 변수</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>lasso.fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glmnet 

625 samples
  5 predictor
  2 classes: 'no', 'yes' 

Pre-processing: centered (6), scaled (6) 
Resampling: Cross-Validated (5 fold) 
Summary of sample sizes: 500, 500, 500, 500, 500 
Resampling results across tuning parameters:

  lambda  Accuracy  Kappa     
  0.000   0.7840    0.53787566
  0.001   0.7840    0.53787566
  0.002   0.7888    0.54713361
  0.003   0.7888    0.54587635
  0.004   0.7840    0.53373303
  0.005   0.7872    0.53898823
  0.006   0.7840    0.53197659
  0.007   0.7840    0.53197400
  0.008   0.7856    0.53507154
  0.009   0.7856    0.53507154
  0.010   0.7840    0.53132186
  0.011   0.7840    0.53132186
  0.012   0.7840    0.53067201
  0.013   0.7840    0.53067201
  0.014   0.7856    0.53379173
  0.015   0.7872    0.53754141
  0.016   0.7872    0.53754141
  0.017   0.7872    0.53754141
  0.018   0.7856    0.53447375
  0.019   0.7856    0.53539055
  0.020   0.7872    0.53933256
  0.021   0.7920    0.54927750
  0.022   0.7936    0.55318733
  0.023   0.7920    0.55005371
  0.024   0.7904    0.54630152
  0.025   0.7904    0.54633807
  0.026   0.7904    0.54633807
  0.027   0.7872    0.54007357
  0.028   0.7872    0.54076382
  0.029   0.7856    0.53773701
  0.030   0.7776    0.52231065
  0.031   0.7776    0.52231065
  0.032   0.7776    0.52231065
  0.033   0.7760    0.51930816
  0.034   0.7760    0.52015488
  0.035   0.7760    0.52015488
  0.036   0.7728    0.51413374
  0.037   0.7712    0.51115833
  0.038   0.7712    0.51115833
  0.039   0.7712    0.51115833
  0.040   0.7712    0.51115833
  0.041   0.7712    0.51115833
  0.042   0.7712    0.51115833
  0.043   0.7712    0.51115833
  0.044   0.7712    0.51115833
  0.045   0.7712    0.51115833
  0.046   0.7728    0.51499913
  0.047   0.7728    0.51499913
  0.048   0.7728    0.51499913
  0.049   0.7728    0.51499913
  0.050   0.7728    0.51499913
  0.051   0.7728    0.51499913
  0.052   0.7728    0.51499913
  0.053   0.7728    0.51499913
  0.054   0.7728    0.51499913
  0.055   0.7728    0.51499913
  0.056   0.7728    0.51499913
  0.057   0.7728    0.51499913
  0.058   0.7728    0.51499913
  0.059   0.7728    0.51499913
  0.060   0.7728    0.51499913
  0.061   0.7728    0.51499913
  0.062   0.7728    0.51499913
  0.063   0.7728    0.51499913
  0.064   0.7728    0.51499913
  0.065   0.7728    0.51499913
  0.066   0.7728    0.51499913
  0.067   0.7728    0.51499913
  0.068   0.7728    0.51499913
  0.069   0.7728    0.51499913
  0.070   0.7728    0.51499913
  0.071   0.7728    0.51499913
  0.072   0.7728    0.51499913
  0.073   0.7728    0.51499913
  0.074   0.7728    0.51499913
  0.075   0.7728    0.51499913
  0.076   0.7728    0.51499913
  0.077   0.7728    0.51499913
  0.078   0.7728    0.51499913
  0.079   0.7728    0.51499913
  0.080   0.7728    0.51499913
  0.081   0.7728    0.51499913
  0.082   0.7728    0.51499913
  0.083   0.7728    0.51499913
  0.084   0.7728    0.51499913
  0.085   0.7728    0.51499913
  0.086   0.7728    0.51499913
  0.087   0.7728    0.51499913
  0.088   0.7728    0.51499913
  0.089   0.7728    0.51499913
  0.090   0.7728    0.51499913
  0.091   0.7728    0.51499913
  0.092   0.7728    0.51499913
  0.093   0.7728    0.51499913
  0.094   0.7728    0.51499913
  0.095   0.7728    0.51499913
  0.096   0.7728    0.51499913
  0.097   0.7728    0.51499913
  0.098   0.7728    0.51499913
  0.099   0.7728    0.51499913
  0.100   0.7728    0.51499913
  0.101   0.7728    0.51499913
  0.102   0.7728    0.51499913
  0.103   0.7728    0.51499913
  0.104   0.7728    0.51499913
  0.105   0.7728    0.51499913
  0.106   0.7728    0.51499913
  0.107   0.7728    0.51499913
  0.108   0.7728    0.51499913
  0.109   0.7728    0.51499913
  0.110   0.7728    0.51499913
  0.111   0.7728    0.51499913
  0.112   0.7728    0.51499913
  0.113   0.7728    0.51499913
  0.114   0.7728    0.51499913
  0.115   0.7728    0.51499913
  0.116   0.7728    0.51499913
  0.117   0.7728    0.51499913
  0.118   0.7728    0.51499913
  0.119   0.7728    0.51499913
  0.120   0.7728    0.51499913
  0.121   0.7728    0.51499913
  0.122   0.7728    0.51499913
  0.123   0.7728    0.51499913
  0.124   0.7728    0.51499913
  0.125   0.7728    0.51499913
  0.126   0.7728    0.51499913
  0.127   0.7728    0.51499913
  0.128   0.7728    0.51499913
  0.129   0.7728    0.51499913
  0.130   0.7728    0.51499913
  0.131   0.7728    0.51499913
  0.132   0.7728    0.51499913
  0.133   0.7680    0.49535288
  0.134   0.7680    0.49535288
  0.135   0.7680    0.49535288
  0.136   0.7680    0.49535288
  0.137   0.7680    0.49535288
  0.138   0.7680    0.49535288
  0.139   0.7680    0.49535288
  0.140   0.7680    0.49535288
  0.141   0.7680    0.49535288
  0.142   0.7616    0.46904664
  0.143   0.7616    0.46904664
  0.144   0.7616    0.46904664
  0.145   0.7616    0.46904664
  0.146   0.7616    0.46904664
  0.147   0.7616    0.46904664
  0.148   0.7616    0.46904664
  0.149   0.7616    0.46904664
  0.150   0.7616    0.46904664
  0.151   0.7616    0.46904664
  0.152   0.7616    0.46904664
  0.153   0.7616    0.46904664
  0.154   0.7616    0.46904664
  0.155   0.7616    0.46904664
  0.156   0.7248    0.35460447
  0.157   0.7248    0.35460447
  0.158   0.7248    0.35460447
  0.159   0.7248    0.35460447
  0.160   0.7248    0.35460447
  0.161   0.7248    0.35460447
  0.162   0.6944    0.26430337
  0.163   0.6944    0.26430337
  0.164   0.6672    0.18156771
  0.165   0.6672    0.18156771
  0.166   0.6672    0.18156771
  0.167   0.6672    0.18156771
  0.168   0.6384    0.08223885
  0.169   0.6384    0.08223885
  0.170   0.6384    0.08223885
  0.171   0.6384    0.08223885
  0.172   0.6384    0.08223885
  0.173   0.6384    0.08223885
  0.174   0.6160    0.00000000
  0.175   0.6160    0.00000000
  0.176   0.6160    0.00000000
  0.177   0.6160    0.00000000
  0.178   0.6160    0.00000000
  0.179   0.6160    0.00000000
  0.180   0.6160    0.00000000
  0.181   0.6160    0.00000000
  0.182   0.6160    0.00000000
  0.183   0.6160    0.00000000
  0.184   0.6160    0.00000000
  0.185   0.6160    0.00000000
  0.186   0.6160    0.00000000
  0.187   0.6160    0.00000000
  0.188   0.6160    0.00000000
  0.189   0.6160    0.00000000
  0.190   0.6160    0.00000000
  0.191   0.6160    0.00000000
  0.192   0.6160    0.00000000
  0.193   0.6160    0.00000000
  0.194   0.6160    0.00000000
  0.195   0.6160    0.00000000
  0.196   0.6160    0.00000000
  0.197   0.6160    0.00000000
  0.198   0.6160    0.00000000
  0.199   0.6160    0.00000000
  0.200   0.6160    0.00000000
  0.201   0.6160    0.00000000
  0.202   0.6160    0.00000000
  0.203   0.6160    0.00000000
  0.204   0.6160    0.00000000
  0.205   0.6160    0.00000000
  0.206   0.6160    0.00000000
  0.207   0.6160    0.00000000
  0.208   0.6160    0.00000000
  0.209   0.6160    0.00000000
  0.210   0.6160    0.00000000
  0.211   0.6160    0.00000000
  0.212   0.6160    0.00000000
  0.213   0.6160    0.00000000
  0.214   0.6160    0.00000000
  0.215   0.6160    0.00000000
  0.216   0.6160    0.00000000
  0.217   0.6160    0.00000000
  0.218   0.6160    0.00000000
  0.219   0.6160    0.00000000
  0.220   0.6160    0.00000000
  0.221   0.6160    0.00000000
  0.222   0.6160    0.00000000
  0.223   0.6160    0.00000000
  0.224   0.6160    0.00000000
  0.225   0.6160    0.00000000
  0.226   0.6160    0.00000000
  0.227   0.6160    0.00000000
  0.228   0.6160    0.00000000
  0.229   0.6160    0.00000000
  0.230   0.6160    0.00000000
  0.231   0.6160    0.00000000
  0.232   0.6160    0.00000000
  0.233   0.6160    0.00000000
  0.234   0.6160    0.00000000
  0.235   0.6160    0.00000000
  0.236   0.6160    0.00000000
  0.237   0.6160    0.00000000
  0.238   0.6160    0.00000000
  0.239   0.6160    0.00000000
  0.240   0.6160    0.00000000
  0.241   0.6160    0.00000000
  0.242   0.6160    0.00000000
  0.243   0.6160    0.00000000
  0.244   0.6160    0.00000000
  0.245   0.6160    0.00000000
  0.246   0.6160    0.00000000
  0.247   0.6160    0.00000000
  0.248   0.6160    0.00000000
  0.249   0.6160    0.00000000
  0.250   0.6160    0.00000000
  0.251   0.6160    0.00000000
  0.252   0.6160    0.00000000
  0.253   0.6160    0.00000000
  0.254   0.6160    0.00000000
  0.255   0.6160    0.00000000
  0.256   0.6160    0.00000000
  0.257   0.6160    0.00000000
  0.258   0.6160    0.00000000
  0.259   0.6160    0.00000000
  0.260   0.6160    0.00000000
  0.261   0.6160    0.00000000
  0.262   0.6160    0.00000000
  0.263   0.6160    0.00000000
  0.264   0.6160    0.00000000
  0.265   0.6160    0.00000000
  0.266   0.6160    0.00000000
  0.267   0.6160    0.00000000
  0.268   0.6160    0.00000000
  0.269   0.6160    0.00000000
  0.270   0.6160    0.00000000
  0.271   0.6160    0.00000000
  0.272   0.6160    0.00000000
  0.273   0.6160    0.00000000
  0.274   0.6160    0.00000000
  0.275   0.6160    0.00000000
  0.276   0.6160    0.00000000
  0.277   0.6160    0.00000000
  0.278   0.6160    0.00000000
  0.279   0.6160    0.00000000
  0.280   0.6160    0.00000000
  0.281   0.6160    0.00000000
  0.282   0.6160    0.00000000
  0.283   0.6160    0.00000000
  0.284   0.6160    0.00000000
  0.285   0.6160    0.00000000
  0.286   0.6160    0.00000000
  0.287   0.6160    0.00000000
  0.288   0.6160    0.00000000
  0.289   0.6160    0.00000000
  0.290   0.6160    0.00000000
  0.291   0.6160    0.00000000
  0.292   0.6160    0.00000000
  0.293   0.6160    0.00000000
  0.294   0.6160    0.00000000
  0.295   0.6160    0.00000000
  0.296   0.6160    0.00000000
  0.297   0.6160    0.00000000
  0.298   0.6160    0.00000000
  0.299   0.6160    0.00000000
  0.300   0.6160    0.00000000
  0.301   0.6160    0.00000000
  0.302   0.6160    0.00000000
  0.303   0.6160    0.00000000
  0.304   0.6160    0.00000000
  0.305   0.6160    0.00000000
  0.306   0.6160    0.00000000
  0.307   0.6160    0.00000000
  0.308   0.6160    0.00000000
  0.309   0.6160    0.00000000
  0.310   0.6160    0.00000000
  0.311   0.6160    0.00000000
  0.312   0.6160    0.00000000
  0.313   0.6160    0.00000000
  0.314   0.6160    0.00000000
  0.315   0.6160    0.00000000
  0.316   0.6160    0.00000000
  0.317   0.6160    0.00000000
  0.318   0.6160    0.00000000
  0.319   0.6160    0.00000000
  0.320   0.6160    0.00000000
  0.321   0.6160    0.00000000
  0.322   0.6160    0.00000000
  0.323   0.6160    0.00000000
  0.324   0.6160    0.00000000
  0.325   0.6160    0.00000000
  0.326   0.6160    0.00000000
  0.327   0.6160    0.00000000
  0.328   0.6160    0.00000000
  0.329   0.6160    0.00000000
  0.330   0.6160    0.00000000
  0.331   0.6160    0.00000000
  0.332   0.6160    0.00000000
  0.333   0.6160    0.00000000
  0.334   0.6160    0.00000000
  0.335   0.6160    0.00000000
  0.336   0.6160    0.00000000
  0.337   0.6160    0.00000000
  0.338   0.6160    0.00000000
  0.339   0.6160    0.00000000
  0.340   0.6160    0.00000000
  0.341   0.6160    0.00000000
  0.342   0.6160    0.00000000
  0.343   0.6160    0.00000000
  0.344   0.6160    0.00000000
  0.345   0.6160    0.00000000
  0.346   0.6160    0.00000000
  0.347   0.6160    0.00000000
  0.348   0.6160    0.00000000
  0.349   0.6160    0.00000000
  0.350   0.6160    0.00000000
  0.351   0.6160    0.00000000
  0.352   0.6160    0.00000000
  0.353   0.6160    0.00000000
  0.354   0.6160    0.00000000
  0.355   0.6160    0.00000000
  0.356   0.6160    0.00000000
  0.357   0.6160    0.00000000
  0.358   0.6160    0.00000000
  0.359   0.6160    0.00000000
  0.360   0.6160    0.00000000
  0.361   0.6160    0.00000000
  0.362   0.6160    0.00000000
  0.363   0.6160    0.00000000
  0.364   0.6160    0.00000000
  0.365   0.6160    0.00000000
  0.366   0.6160    0.00000000
  0.367   0.6160    0.00000000
  0.368   0.6160    0.00000000
  0.369   0.6160    0.00000000
  0.370   0.6160    0.00000000
  0.371   0.6160    0.00000000
  0.372   0.6160    0.00000000
  0.373   0.6160    0.00000000
  0.374   0.6160    0.00000000
  0.375   0.6160    0.00000000
  0.376   0.6160    0.00000000
  0.377   0.6160    0.00000000
  0.378   0.6160    0.00000000
  0.379   0.6160    0.00000000
  0.380   0.6160    0.00000000
  0.381   0.6160    0.00000000
  0.382   0.6160    0.00000000
  0.383   0.6160    0.00000000
  0.384   0.6160    0.00000000
  0.385   0.6160    0.00000000
  0.386   0.6160    0.00000000
  0.387   0.6160    0.00000000
  0.388   0.6160    0.00000000
  0.389   0.6160    0.00000000
  0.390   0.6160    0.00000000
  0.391   0.6160    0.00000000
  0.392   0.6160    0.00000000
  0.393   0.6160    0.00000000
  0.394   0.6160    0.00000000
  0.395   0.6160    0.00000000
  0.396   0.6160    0.00000000
  0.397   0.6160    0.00000000
  0.398   0.6160    0.00000000
  0.399   0.6160    0.00000000
  0.400   0.6160    0.00000000
  0.401   0.6160    0.00000000
  0.402   0.6160    0.00000000
  0.403   0.6160    0.00000000
  0.404   0.6160    0.00000000
  0.405   0.6160    0.00000000
  0.406   0.6160    0.00000000
  0.407   0.6160    0.00000000
  0.408   0.6160    0.00000000
  0.409   0.6160    0.00000000
  0.410   0.6160    0.00000000
  0.411   0.6160    0.00000000
  0.412   0.6160    0.00000000
  0.413   0.6160    0.00000000
  0.414   0.6160    0.00000000
  0.415   0.6160    0.00000000
  0.416   0.6160    0.00000000
  0.417   0.6160    0.00000000
  0.418   0.6160    0.00000000
  0.419   0.6160    0.00000000
  0.420   0.6160    0.00000000
  0.421   0.6160    0.00000000
  0.422   0.6160    0.00000000
  0.423   0.6160    0.00000000
  0.424   0.6160    0.00000000
  0.425   0.6160    0.00000000
  0.426   0.6160    0.00000000
  0.427   0.6160    0.00000000
  0.428   0.6160    0.00000000
  0.429   0.6160    0.00000000
  0.430   0.6160    0.00000000
  0.431   0.6160    0.00000000
  0.432   0.6160    0.00000000
  0.433   0.6160    0.00000000
  0.434   0.6160    0.00000000
  0.435   0.6160    0.00000000
  0.436   0.6160    0.00000000
  0.437   0.6160    0.00000000
  0.438   0.6160    0.00000000
  0.439   0.6160    0.00000000
  0.440   0.6160    0.00000000
  0.441   0.6160    0.00000000
  0.442   0.6160    0.00000000
  0.443   0.6160    0.00000000
  0.444   0.6160    0.00000000
  0.445   0.6160    0.00000000
  0.446   0.6160    0.00000000
  0.447   0.6160    0.00000000
  0.448   0.6160    0.00000000
  0.449   0.6160    0.00000000
  0.450   0.6160    0.00000000
  0.451   0.6160    0.00000000
  0.452   0.6160    0.00000000
  0.453   0.6160    0.00000000
  0.454   0.6160    0.00000000
  0.455   0.6160    0.00000000
  0.456   0.6160    0.00000000
  0.457   0.6160    0.00000000
  0.458   0.6160    0.00000000
  0.459   0.6160    0.00000000
  0.460   0.6160    0.00000000
  0.461   0.6160    0.00000000
  0.462   0.6160    0.00000000
  0.463   0.6160    0.00000000
  0.464   0.6160    0.00000000
  0.465   0.6160    0.00000000
  0.466   0.6160    0.00000000
  0.467   0.6160    0.00000000
  0.468   0.6160    0.00000000
  0.469   0.6160    0.00000000
  0.470   0.6160    0.00000000
  0.471   0.6160    0.00000000
  0.472   0.6160    0.00000000
  0.473   0.6160    0.00000000
  0.474   0.6160    0.00000000
  0.475   0.6160    0.00000000
  0.476   0.6160    0.00000000
  0.477   0.6160    0.00000000
  0.478   0.6160    0.00000000
  0.479   0.6160    0.00000000
  0.480   0.6160    0.00000000
  0.481   0.6160    0.00000000
  0.482   0.6160    0.00000000
  0.483   0.6160    0.00000000
  0.484   0.6160    0.00000000
  0.485   0.6160    0.00000000
  0.486   0.6160    0.00000000
  0.487   0.6160    0.00000000
  0.488   0.6160    0.00000000
  0.489   0.6160    0.00000000
  0.490   0.6160    0.00000000
  0.491   0.6160    0.00000000
  0.492   0.6160    0.00000000
  0.493   0.6160    0.00000000
  0.494   0.6160    0.00000000
  0.495   0.6160    0.00000000
  0.496   0.6160    0.00000000
  0.497   0.6160    0.00000000
  0.498   0.6160    0.00000000
  0.499   0.6160    0.00000000
  0.500   0.6160    0.00000000
  0.501   0.6160    0.00000000
  0.502   0.6160    0.00000000
  0.503   0.6160    0.00000000
  0.504   0.6160    0.00000000
  0.505   0.6160    0.00000000
  0.506   0.6160    0.00000000
  0.507   0.6160    0.00000000
  0.508   0.6160    0.00000000
  0.509   0.6160    0.00000000
  0.510   0.6160    0.00000000
  0.511   0.6160    0.00000000
  0.512   0.6160    0.00000000
  0.513   0.6160    0.00000000
  0.514   0.6160    0.00000000
  0.515   0.6160    0.00000000
  0.516   0.6160    0.00000000
  0.517   0.6160    0.00000000
  0.518   0.6160    0.00000000
  0.519   0.6160    0.00000000
  0.520   0.6160    0.00000000
  0.521   0.6160    0.00000000
  0.522   0.6160    0.00000000
  0.523   0.6160    0.00000000
  0.524   0.6160    0.00000000
  0.525   0.6160    0.00000000
  0.526   0.6160    0.00000000
  0.527   0.6160    0.00000000
  0.528   0.6160    0.00000000
  0.529   0.6160    0.00000000
  0.530   0.6160    0.00000000
  0.531   0.6160    0.00000000
  0.532   0.6160    0.00000000
  0.533   0.6160    0.00000000
  0.534   0.6160    0.00000000
  0.535   0.6160    0.00000000
  0.536   0.6160    0.00000000
  0.537   0.6160    0.00000000
  0.538   0.6160    0.00000000
  0.539   0.6160    0.00000000
  0.540   0.6160    0.00000000
  0.541   0.6160    0.00000000
  0.542   0.6160    0.00000000
  0.543   0.6160    0.00000000
  0.544   0.6160    0.00000000
  0.545   0.6160    0.00000000
  0.546   0.6160    0.00000000
  0.547   0.6160    0.00000000
  0.548   0.6160    0.00000000
  0.549   0.6160    0.00000000
  0.550   0.6160    0.00000000
  0.551   0.6160    0.00000000
  0.552   0.6160    0.00000000
  0.553   0.6160    0.00000000
  0.554   0.6160    0.00000000
  0.555   0.6160    0.00000000
  0.556   0.6160    0.00000000
  0.557   0.6160    0.00000000
  0.558   0.6160    0.00000000
  0.559   0.6160    0.00000000
  0.560   0.6160    0.00000000
  0.561   0.6160    0.00000000
  0.562   0.6160    0.00000000
  0.563   0.6160    0.00000000
  0.564   0.6160    0.00000000
  0.565   0.6160    0.00000000
  0.566   0.6160    0.00000000
  0.567   0.6160    0.00000000
  0.568   0.6160    0.00000000
  0.569   0.6160    0.00000000
  0.570   0.6160    0.00000000
  0.571   0.6160    0.00000000
  0.572   0.6160    0.00000000
  0.573   0.6160    0.00000000
  0.574   0.6160    0.00000000
  0.575   0.6160    0.00000000
  0.576   0.6160    0.00000000
  0.577   0.6160    0.00000000
  0.578   0.6160    0.00000000
  0.579   0.6160    0.00000000
  0.580   0.6160    0.00000000
  0.581   0.6160    0.00000000
  0.582   0.6160    0.00000000
  0.583   0.6160    0.00000000
  0.584   0.6160    0.00000000
  0.585   0.6160    0.00000000
  0.586   0.6160    0.00000000
  0.587   0.6160    0.00000000
  0.588   0.6160    0.00000000
  0.589   0.6160    0.00000000
  0.590   0.6160    0.00000000
  0.591   0.6160    0.00000000
  0.592   0.6160    0.00000000
  0.593   0.6160    0.00000000
  0.594   0.6160    0.00000000
  0.595   0.6160    0.00000000
  0.596   0.6160    0.00000000
  0.597   0.6160    0.00000000
  0.598   0.6160    0.00000000
  0.599   0.6160    0.00000000
  0.600   0.6160    0.00000000
  0.601   0.6160    0.00000000
  0.602   0.6160    0.00000000
  0.603   0.6160    0.00000000
  0.604   0.6160    0.00000000
  0.605   0.6160    0.00000000
  0.606   0.6160    0.00000000
  0.607   0.6160    0.00000000
  0.608   0.6160    0.00000000
  0.609   0.6160    0.00000000
  0.610   0.6160    0.00000000
  0.611   0.6160    0.00000000
  0.612   0.6160    0.00000000
  0.613   0.6160    0.00000000
  0.614   0.6160    0.00000000
  0.615   0.6160    0.00000000
  0.616   0.6160    0.00000000
  0.617   0.6160    0.00000000
  0.618   0.6160    0.00000000
  0.619   0.6160    0.00000000
  0.620   0.6160    0.00000000
  0.621   0.6160    0.00000000
  0.622   0.6160    0.00000000
  0.623   0.6160    0.00000000
  0.624   0.6160    0.00000000
  0.625   0.6160    0.00000000
  0.626   0.6160    0.00000000
  0.627   0.6160    0.00000000
  0.628   0.6160    0.00000000
  0.629   0.6160    0.00000000
  0.630   0.6160    0.00000000
  0.631   0.6160    0.00000000
  0.632   0.6160    0.00000000
  0.633   0.6160    0.00000000
  0.634   0.6160    0.00000000
  0.635   0.6160    0.00000000
  0.636   0.6160    0.00000000
  0.637   0.6160    0.00000000
  0.638   0.6160    0.00000000
  0.639   0.6160    0.00000000
  0.640   0.6160    0.00000000
  0.641   0.6160    0.00000000
  0.642   0.6160    0.00000000
  0.643   0.6160    0.00000000
  0.644   0.6160    0.00000000
  0.645   0.6160    0.00000000
  0.646   0.6160    0.00000000
  0.647   0.6160    0.00000000
  0.648   0.6160    0.00000000
  0.649   0.6160    0.00000000
  0.650   0.6160    0.00000000
  0.651   0.6160    0.00000000
  0.652   0.6160    0.00000000
  0.653   0.6160    0.00000000
  0.654   0.6160    0.00000000
  0.655   0.6160    0.00000000
  0.656   0.6160    0.00000000
  0.657   0.6160    0.00000000
  0.658   0.6160    0.00000000
  0.659   0.6160    0.00000000
  0.660   0.6160    0.00000000
  0.661   0.6160    0.00000000
  0.662   0.6160    0.00000000
  0.663   0.6160    0.00000000
  0.664   0.6160    0.00000000
  0.665   0.6160    0.00000000
  0.666   0.6160    0.00000000
  0.667   0.6160    0.00000000
  0.668   0.6160    0.00000000
  0.669   0.6160    0.00000000
  0.670   0.6160    0.00000000
  0.671   0.6160    0.00000000
  0.672   0.6160    0.00000000
  0.673   0.6160    0.00000000
  0.674   0.6160    0.00000000
  0.675   0.6160    0.00000000
  0.676   0.6160    0.00000000
  0.677   0.6160    0.00000000
  0.678   0.6160    0.00000000
  0.679   0.6160    0.00000000
  0.680   0.6160    0.00000000
  0.681   0.6160    0.00000000
  0.682   0.6160    0.00000000
  0.683   0.6160    0.00000000
  0.684   0.6160    0.00000000
  0.685   0.6160    0.00000000
  0.686   0.6160    0.00000000
  0.687   0.6160    0.00000000
  0.688   0.6160    0.00000000
  0.689   0.6160    0.00000000
  0.690   0.6160    0.00000000
  0.691   0.6160    0.00000000
  0.692   0.6160    0.00000000
  0.693   0.6160    0.00000000
  0.694   0.6160    0.00000000
  0.695   0.6160    0.00000000
  0.696   0.6160    0.00000000
  0.697   0.6160    0.00000000
  0.698   0.6160    0.00000000
  0.699   0.6160    0.00000000
  0.700   0.6160    0.00000000
  0.701   0.6160    0.00000000
  0.702   0.6160    0.00000000
  0.703   0.6160    0.00000000
  0.704   0.6160    0.00000000
  0.705   0.6160    0.00000000
  0.706   0.6160    0.00000000
  0.707   0.6160    0.00000000
  0.708   0.6160    0.00000000
  0.709   0.6160    0.00000000
  0.710   0.6160    0.00000000
  0.711   0.6160    0.00000000
  0.712   0.6160    0.00000000
  0.713   0.6160    0.00000000
  0.714   0.6160    0.00000000
  0.715   0.6160    0.00000000
  0.716   0.6160    0.00000000
  0.717   0.6160    0.00000000
  0.718   0.6160    0.00000000
  0.719   0.6160    0.00000000
  0.720   0.6160    0.00000000
  0.721   0.6160    0.00000000
  0.722   0.6160    0.00000000
  0.723   0.6160    0.00000000
  0.724   0.6160    0.00000000
  0.725   0.6160    0.00000000
  0.726   0.6160    0.00000000
  0.727   0.6160    0.00000000
  0.728   0.6160    0.00000000
  0.729   0.6160    0.00000000
  0.730   0.6160    0.00000000
  0.731   0.6160    0.00000000
  0.732   0.6160    0.00000000
  0.733   0.6160    0.00000000
  0.734   0.6160    0.00000000
  0.735   0.6160    0.00000000
  0.736   0.6160    0.00000000
  0.737   0.6160    0.00000000
  0.738   0.6160    0.00000000
  0.739   0.6160    0.00000000
  0.740   0.6160    0.00000000
  0.741   0.6160    0.00000000
  0.742   0.6160    0.00000000
  0.743   0.6160    0.00000000
  0.744   0.6160    0.00000000
  0.745   0.6160    0.00000000
  0.746   0.6160    0.00000000
  0.747   0.6160    0.00000000
  0.748   0.6160    0.00000000
  0.749   0.6160    0.00000000
  0.750   0.6160    0.00000000
  0.751   0.6160    0.00000000
  0.752   0.6160    0.00000000
  0.753   0.6160    0.00000000
  0.754   0.6160    0.00000000
  0.755   0.6160    0.00000000
  0.756   0.6160    0.00000000
  0.757   0.6160    0.00000000
  0.758   0.6160    0.00000000
  0.759   0.6160    0.00000000
  0.760   0.6160    0.00000000
  0.761   0.6160    0.00000000
  0.762   0.6160    0.00000000
  0.763   0.6160    0.00000000
  0.764   0.6160    0.00000000
  0.765   0.6160    0.00000000
  0.766   0.6160    0.00000000
  0.767   0.6160    0.00000000
  0.768   0.6160    0.00000000
  0.769   0.6160    0.00000000
  0.770   0.6160    0.00000000
  0.771   0.6160    0.00000000
  0.772   0.6160    0.00000000
  0.773   0.6160    0.00000000
  0.774   0.6160    0.00000000
  0.775   0.6160    0.00000000
  0.776   0.6160    0.00000000
  0.777   0.6160    0.00000000
  0.778   0.6160    0.00000000
  0.779   0.6160    0.00000000
  0.780   0.6160    0.00000000
  0.781   0.6160    0.00000000
  0.782   0.6160    0.00000000
  0.783   0.6160    0.00000000
  0.784   0.6160    0.00000000
  0.785   0.6160    0.00000000
  0.786   0.6160    0.00000000
  0.787   0.6160    0.00000000
  0.788   0.6160    0.00000000
  0.789   0.6160    0.00000000
  0.790   0.6160    0.00000000
  0.791   0.6160    0.00000000
  0.792   0.6160    0.00000000
  0.793   0.6160    0.00000000
  0.794   0.6160    0.00000000
  0.795   0.6160    0.00000000
  0.796   0.6160    0.00000000
  0.797   0.6160    0.00000000
  0.798   0.6160    0.00000000
  0.799   0.6160    0.00000000
  0.800   0.6160    0.00000000
  0.801   0.6160    0.00000000
  0.802   0.6160    0.00000000
  0.803   0.6160    0.00000000
  0.804   0.6160    0.00000000
  0.805   0.6160    0.00000000
  0.806   0.6160    0.00000000
  0.807   0.6160    0.00000000
  0.808   0.6160    0.00000000
  0.809   0.6160    0.00000000
  0.810   0.6160    0.00000000
  0.811   0.6160    0.00000000
  0.812   0.6160    0.00000000
  0.813   0.6160    0.00000000
  0.814   0.6160    0.00000000
  0.815   0.6160    0.00000000
  0.816   0.6160    0.00000000
  0.817   0.6160    0.00000000
  0.818   0.6160    0.00000000
  0.819   0.6160    0.00000000
  0.820   0.6160    0.00000000
  0.821   0.6160    0.00000000
  0.822   0.6160    0.00000000
  0.823   0.6160    0.00000000
  0.824   0.6160    0.00000000
  0.825   0.6160    0.00000000
  0.826   0.6160    0.00000000
  0.827   0.6160    0.00000000
  0.828   0.6160    0.00000000
  0.829   0.6160    0.00000000
  0.830   0.6160    0.00000000
  0.831   0.6160    0.00000000
  0.832   0.6160    0.00000000
  0.833   0.6160    0.00000000
  0.834   0.6160    0.00000000
  0.835   0.6160    0.00000000
  0.836   0.6160    0.00000000
  0.837   0.6160    0.00000000
  0.838   0.6160    0.00000000
  0.839   0.6160    0.00000000
  0.840   0.6160    0.00000000
  0.841   0.6160    0.00000000
  0.842   0.6160    0.00000000
  0.843   0.6160    0.00000000
  0.844   0.6160    0.00000000
  0.845   0.6160    0.00000000
  0.846   0.6160    0.00000000
  0.847   0.6160    0.00000000
  0.848   0.6160    0.00000000
  0.849   0.6160    0.00000000
  0.850   0.6160    0.00000000
  0.851   0.6160    0.00000000
  0.852   0.6160    0.00000000
  0.853   0.6160    0.00000000
  0.854   0.6160    0.00000000
  0.855   0.6160    0.00000000
  0.856   0.6160    0.00000000
  0.857   0.6160    0.00000000
  0.858   0.6160    0.00000000
  0.859   0.6160    0.00000000
  0.860   0.6160    0.00000000
  0.861   0.6160    0.00000000
  0.862   0.6160    0.00000000
  0.863   0.6160    0.00000000
  0.864   0.6160    0.00000000
  0.865   0.6160    0.00000000
  0.866   0.6160    0.00000000
  0.867   0.6160    0.00000000
  0.868   0.6160    0.00000000
  0.869   0.6160    0.00000000
  0.870   0.6160    0.00000000
  0.871   0.6160    0.00000000
  0.872   0.6160    0.00000000
  0.873   0.6160    0.00000000
  0.874   0.6160    0.00000000
  0.875   0.6160    0.00000000
  0.876   0.6160    0.00000000
  0.877   0.6160    0.00000000
  0.878   0.6160    0.00000000
  0.879   0.6160    0.00000000
  0.880   0.6160    0.00000000
  0.881   0.6160    0.00000000
  0.882   0.6160    0.00000000
  0.883   0.6160    0.00000000
  0.884   0.6160    0.00000000
  0.885   0.6160    0.00000000
  0.886   0.6160    0.00000000
  0.887   0.6160    0.00000000
  0.888   0.6160    0.00000000
  0.889   0.6160    0.00000000
  0.890   0.6160    0.00000000
  0.891   0.6160    0.00000000
  0.892   0.6160    0.00000000
  0.893   0.6160    0.00000000
  0.894   0.6160    0.00000000
  0.895   0.6160    0.00000000
  0.896   0.6160    0.00000000
  0.897   0.6160    0.00000000
  0.898   0.6160    0.00000000
  0.899   0.6160    0.00000000
  0.900   0.6160    0.00000000
  0.901   0.6160    0.00000000
  0.902   0.6160    0.00000000
  0.903   0.6160    0.00000000
  0.904   0.6160    0.00000000
  0.905   0.6160    0.00000000
  0.906   0.6160    0.00000000
  0.907   0.6160    0.00000000
  0.908   0.6160    0.00000000
  0.909   0.6160    0.00000000
  0.910   0.6160    0.00000000
  0.911   0.6160    0.00000000
  0.912   0.6160    0.00000000
  0.913   0.6160    0.00000000
  0.914   0.6160    0.00000000
  0.915   0.6160    0.00000000
  0.916   0.6160    0.00000000
  0.917   0.6160    0.00000000
  0.918   0.6160    0.00000000
  0.919   0.6160    0.00000000
  0.920   0.6160    0.00000000
  0.921   0.6160    0.00000000
  0.922   0.6160    0.00000000
  0.923   0.6160    0.00000000
  0.924   0.6160    0.00000000
  0.925   0.6160    0.00000000
  0.926   0.6160    0.00000000
  0.927   0.6160    0.00000000
  0.928   0.6160    0.00000000
  0.929   0.6160    0.00000000
  0.930   0.6160    0.00000000
  0.931   0.6160    0.00000000
  0.932   0.6160    0.00000000
  0.933   0.6160    0.00000000
  0.934   0.6160    0.00000000
  0.935   0.6160    0.00000000
  0.936   0.6160    0.00000000
  0.937   0.6160    0.00000000
  0.938   0.6160    0.00000000
  0.939   0.6160    0.00000000
  0.940   0.6160    0.00000000
  0.941   0.6160    0.00000000
  0.942   0.6160    0.00000000
  0.943   0.6160    0.00000000
  0.944   0.6160    0.00000000
  0.945   0.6160    0.00000000
  0.946   0.6160    0.00000000
  0.947   0.6160    0.00000000
  0.948   0.6160    0.00000000
  0.949   0.6160    0.00000000
  0.950   0.6160    0.00000000
  0.951   0.6160    0.00000000
  0.952   0.6160    0.00000000
  0.953   0.6160    0.00000000
  0.954   0.6160    0.00000000
  0.955   0.6160    0.00000000
  0.956   0.6160    0.00000000
  0.957   0.6160    0.00000000
  0.958   0.6160    0.00000000
  0.959   0.6160    0.00000000
  0.960   0.6160    0.00000000
  0.961   0.6160    0.00000000
  0.962   0.6160    0.00000000
  0.963   0.6160    0.00000000
  0.964   0.6160    0.00000000
  0.965   0.6160    0.00000000
  0.966   0.6160    0.00000000
  0.967   0.6160    0.00000000
  0.968   0.6160    0.00000000
  0.969   0.6160    0.00000000
  0.970   0.6160    0.00000000
  0.971   0.6160    0.00000000
  0.972   0.6160    0.00000000
  0.973   0.6160    0.00000000
  0.974   0.6160    0.00000000
  0.975   0.6160    0.00000000
  0.976   0.6160    0.00000000
  0.977   0.6160    0.00000000
  0.978   0.6160    0.00000000
  0.979   0.6160    0.00000000
  0.980   0.6160    0.00000000
  0.981   0.6160    0.00000000
  0.982   0.6160    0.00000000
  0.983   0.6160    0.00000000
  0.984   0.6160    0.00000000
  0.985   0.6160    0.00000000
  0.986   0.6160    0.00000000
  0.987   0.6160    0.00000000
  0.988   0.6160    0.00000000
  0.989   0.6160    0.00000000
  0.990   0.6160    0.00000000
  0.991   0.6160    0.00000000
  0.992   0.6160    0.00000000
  0.993   0.6160    0.00000000
  0.994   0.6160    0.00000000
  0.995   0.6160    0.00000000
  0.996   0.6160    0.00000000
  0.997   0.6160    0.00000000
  0.998   0.6160    0.00000000
  0.999   0.6160    0.00000000
  1.000   0.6160    0.00000000

Tuning parameter 'alpha' was held constant at a value of 1
Accuracy was used to select the optimal model using the largest value.
The final values used for the model were alpha = 1 and lambda = 0.022.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lasso.fit)                                                       <span class="co"># Plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LASSO_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>lasso.fit<span class="sc">$</span>bestTune                                                    <span class="co"># lambda의 최적값</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   alpha lambda
23     1  0.022</code></pre>
</div>
</div>
<p><code>Result!</code> <code>lambda</code> = 0.022일 때 정확도가 가장 높은 것을 알 수 있으며, <code>lambda</code> = 0.022를 가지는 모형을 최적의 훈련된 모형으로 선택한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coef</span>(lasso.fit<span class="sc">$</span>finalModel, lasso.fit<span class="sc">$</span>bestTune<span class="sc">$</span>lambda), <span class="dv">3</span>)       <span class="co"># lambda의 최적값에 대한 회귀계수 추정치</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>7 x 1 sparse Matrix of class "dgCMatrix"
                s1
(Intercept) -0.601
Pclass2     -0.036
Pclass3     -0.690
Sexmale     -1.052
Age         -0.193
Fare         0.112
FamSize     -0.128</code></pre>
</div>
</div>
<p><code>Result!</code> 데이터 “titanic.trd.Imp”의 Target “Survived”은 “no”와 “yes” 2개의 클래스를 가지며, “Factor” 변환하면 알파벳순으로 수준을 부여하기 때문에 “yes”가 두 번째 클래스가 된다. 즉, “yes”에 속할 확률(= 탑승객이 생존할 확률)을 <span class="math inline">\(p\)</span>라고 할 때, 추정된 회귀계수를 이용하여 다음과 같은 모형식을 얻을 수 있다. <span class="math display">\[
\begin{align*}
\log{\frac{p}{1-p}} = &amp;-0.601 - 0.036 Z_{\text{Pclass2}} - 0.690 Z_{\text{Pclass3}} -1.052 Z_{\text{Sexmale}} \\
                      &amp;-0.193 Z_{\text{Age}} +0.112 Z_{\text{Fare}} - 0.128 Z_{\text{FamSize}}
\end{align*}
\]</span> 여기서, <span class="math inline">\(Z_{\text{예측 변수}}\)</span>는 표준화한 예측 변수를 의미한다.<br>
범주형 예측 변수(“Pclass”, “Sex”)는 더미 변환이 수행되었는데, 예를 들어, <code>Pclass2</code>는 탑승객의 티켓 등급이 2등급인 경우 “1”값을 가지고 2등급이 아니면 “0”값을 가진다.</p>
</section>
<section id="모형-평가" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="모형-평가"><span class="header-section-number">7.7</span> 모형 평가</h2>
<p><code>Caution!</code> 모형 평가를 위해 <code>Test Dataset</code>에 대한 <code>예측 class/확률</code> 이 필요하며, 함수 <code>predict()</code>를 이용하여 생성한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 예측 class 생성</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>test.lasso.class <span class="ot">&lt;-</span> <span class="fu">predict</span>(lasso.fit, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">newdata =</span> titanic.ted.Imp[,<span class="sc">-</span><span class="dv">1</span>])   <span class="co"># Test Dataset including Only 예측 변수  </span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>test.lasso.class <span class="sc">%&gt;%</span>                                      </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  as_tibble</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 266 × 1
   value
   &lt;fct&gt;
 1 yes  
 2 no   
 3 no   
 4 yes  
 5 no   
 6 no   
 7 yes  
 8 no   
 9 no   
10 yes  
# ℹ 256 more rows</code></pre>
</div>
</div>
<p><br></p>
<section id="confusionmatrix" class="level3" data-number="7.7.1">
<h3 data-number="7.7.1" class="anchored" data-anchor-id="confusionmatrix"><span class="header-section-number">7.7.1</span> ConfusionMatrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>CM   <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(test.lasso.class, titanic.ted.Imp<span class="sc">$</span>Survived, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">positive =</span> <span class="st">"yes"</span>)        <span class="co"># confusionMatrix(예측 class, 실제 class, positive = "관심 class")</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>CM</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  no yes
       no  151  33
       yes  13  69
                                          
               Accuracy : 0.8271          
                 95% CI : (0.7762, 0.8705)
    No Information Rate : 0.6165          
    P-Value [Acc &gt; NIR] : 6.692e-14       
                                          
                  Kappa : 0.6202          
                                          
 Mcnemar's Test P-Value : 0.005088        
                                          
            Sensitivity : 0.6765          
            Specificity : 0.9207          
         Pos Pred Value : 0.8415          
         Neg Pred Value : 0.8207          
             Prevalence : 0.3835          
         Detection Rate : 0.2594          
   Detection Prevalence : 0.3083          
      Balanced Accuracy : 0.7986          
                                          
       'Positive' Class : yes             
                                          </code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="roc-곡선" class="level3" data-number="7.7.2">
<h3 data-number="7.7.2" class="anchored" data-anchor-id="roc-곡선"><span class="header-section-number">7.7.2</span> ROC 곡선</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 예측 확률 생성</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>test.lasso.prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(lasso.fit, </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">newdata =</span> titanic.ted.Imp[,<span class="sc">-</span><span class="dv">1</span>],<span class="co"># Test Dataset including Only 예측 변수 </span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">type =</span> <span class="st">"prob"</span>)                 <span class="co"># 예측 확률 생성</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>test.lasso.prob <span class="sc">%&gt;%</span>                                                         </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  as_tibble</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 266 × 2
      no   yes
   &lt;dbl&gt; &lt;dbl&gt;
 1 0.177 0.823
 2 0.701 0.299
 3 0.862 0.138
 4 0.242 0.758
 5 0.870 0.130
 6 0.676 0.324
 7 0.395 0.605
 8 0.580 0.420
 9 0.879 0.121
10 0.149 0.851
# ℹ 256 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>test.lasso.prob <span class="ot">&lt;-</span> test.lasso.prob[,<span class="dv">2</span>]                 <span class="co"># "Survived = yes"에 대한 예측 확률</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>ac  <span class="ot">&lt;-</span> titanic.ted.Imp<span class="sc">$</span>Survived                        <span class="co"># Test Dataset의 실제 class </span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>pp  <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(test.lasso.prob)                     <span class="co"># 예측 확률을 수치형으로 변환</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="package-proc" class="level4" data-number="7.7.2.1">
<h4 data-number="7.7.2.1" class="anchored" data-anchor-id="package-proc"><span class="header-section-number">7.7.2.1</span> Package “pROC”</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(<span class="st">"pROC"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>lasso.roc  <span class="ot">&lt;-</span> <span class="fu">roc</span>(ac, pp, <span class="at">plot =</span> T, <span class="at">col =</span> <span class="st">"gray"</span>)      <span class="co"># roc(실제 class, 예측 확률)</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>auc        <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">auc</span>(lasso.roc), <span class="dv">3</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> auc, <span class="at">bty =</span> <span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LASSO_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>Caution!</code> Package <code>"pROC"</code>를 통해 출력한 ROC 곡선은 다양한 함수를 이용해서 그래프를 수정할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 함수 plot.roc() 이용</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.roc</span>(lasso.roc,   </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">col=</span><span class="st">"gray"</span>,                                   <span class="co"># Line Color</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">print.auc =</span> <span class="cn">TRUE</span>,                             <span class="co"># AUC 출력 여부</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">print.auc.col =</span> <span class="st">"red"</span>,                        <span class="co"># AUC 글씨 색깔</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">print.thres =</span> <span class="cn">TRUE</span>,                           <span class="co"># Cutoff Value 출력 여부</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">print.thres.pch =</span> <span class="dv">19</span>,                         <span class="co"># Cutoff Value를 표시하는 도형 모양</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">print.thres.col =</span> <span class="st">"red"</span>,                      <span class="co"># Cutoff Value를 표시하는 도형의 색깔</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">auc.polygon =</span> <span class="cn">TRUE</span>,                           <span class="co"># 곡선 아래 면적에 대한 여부</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">auc.polygon.col =</span> <span class="st">"gray90"</span>)                   <span class="co"># 곡선 아래 면적의 색깔</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LASSO_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 함수 ggroc() 이용</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggroc</span>(lasso.roc) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.9</span>, <span class="at">y =</span> <span class="fl">1.0</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"AUC = "</span>, auc),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="at">size =</span> <span class="dv">5</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LASSO_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="package-epi" class="level4" data-number="7.7.2.2">
<h4 data-number="7.7.2.2" class="anchored" data-anchor-id="package-epi"><span class="header-section-number">7.7.2.2</span> Package “Epi”</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(<span class="st">"Epi"</span>)       </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install_version("etm", version = "1.1", repos = "http://cran.us.r-project.org")</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ROC</span>(pp, ac, <span class="at">plot =</span> <span class="st">"ROC"</span>)                              <span class="co"># ROC(예측 확률, 실제 class)  </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LASSO_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="package-rocr" class="level4" data-number="7.7.2.3">
<h4 data-number="7.7.2.3" class="anchored" data-anchor-id="package-rocr"><span class="header-section-number">7.7.2.3</span> Package “ROCR”</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(<span class="st">"ROCR"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>lasso.pred <span class="ot">&lt;-</span> <span class="fu">prediction</span>(pp, ac)                       <span class="co"># prediction(예측 확률, 실제 class) </span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>lasso.perf <span class="ot">&lt;-</span> <span class="fu">performance</span>(lasso.pred, <span class="st">"tpr"</span>, <span class="st">"fpr"</span>)    <span class="co"># performance(, "민감도", "1-특이도")                      </span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lasso.perf, <span class="at">col =</span> <span class="st">"gray"</span>)                         <span class="co"># ROC Curve</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>perf.auc   <span class="ot">&lt;-</span> <span class="fu">performance</span>(lasso.pred, <span class="st">"auc"</span>)           <span class="co"># AUC</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>auc        <span class="ot">&lt;-</span> <span class="fu">attributes</span>(perf.auc)<span class="sc">$</span>y.values</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> auc, <span class="at">bty =</span> <span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LASSO_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="향상-차트" class="level3" data-number="7.7.3">
<h3 data-number="7.7.3" class="anchored" data-anchor-id="향상-차트"><span class="header-section-number">7.7.3</span> 향상 차트</h3>
<section id="package-rocr-1" class="level4" data-number="7.7.3.1">
<h4 data-number="7.7.3.1" class="anchored" data-anchor-id="package-rocr-1"><span class="header-section-number">7.7.3.1</span> Package “ROCR”</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>lasso.perf <span class="ot">&lt;-</span> <span class="fu">performance</span>(lasso.pred, <span class="st">"lift"</span>, <span class="st">"rpp"</span>)   <span class="co"># Lift Chart                      </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lasso.perf, <span class="at">main =</span> <span class="st">"lift curve"</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">colorize =</span> T,                                     <span class="co"># Coloring according to cutoff </span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd =</span> <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LASSO_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./SVM_rd.html" class="pagination-link" aria-label="Support Vector Machine with Radial Basis Kernel">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Support Vector Machine with Radial Basis Kernel</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ridge.html" class="pagination-link" aria-label="Ridge Regression">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Ridge Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/JJJJYE/ML_book2/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>